models/create_bio_page.py
from flask_login import UserMixin
from extensions import db
from sqlalchemy.orm import relationship
import datetime
from sqlalchemy import extract, func
from func import hex_id


class CreateBioPage(UserMixin, db.Model):
    __tablename__ = "bio_page"
    id = db.Column(db.String(50), primary_key=True, default=hex_id)
    # bio_page_id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.String(50), db.ForeignKey("users.id"))
    created_at = db.Column(db.DateTime, nullable=False, default=db.func.now())
    bio_name = db.Column(db.String(250), default="")
    clicks = db.Column(db.Integer, default=0)
    links = relationship("CreateBioLinkEntries", backref="entries")


# clicks record model
class BioPageClicks(db.Model):
    __tablename__ = "bio_page_clicks"
    id = db.Column(db.String(50), primary_key=True, default=hex_id)
    count = db.Column(db.Integer, default=0)
    bio_page_id = db.Column(db.String(50), db.ForeignKey("bio_page.id"))
    created = db.Column(db.DateTime, nullable=False, default=db.func.now())

    def __repr__(self):
        return f"Clicks('{self.bio_page_id}', '{self.created}')"

    def save(self):
        db.session.add(self)
        db.session.commit()

    def save_commit(self):
        db.session.commit()


class BioPageClickLocation(db.Model):
    __tablename__ = "bio_page_click_location"
    id = db.Column(db.String(50), primary_key=True, default=hex_id)
    ip_address = db.Column(db.String(250))
    country = db.Column(db.String(250))
    city = db.Column(db.String(250))
    device = db.Column(db.String(250))
    browser = db.Column(db.String(250))
    bio_page_id = db.Column(db.String(50), db.ForeignKey("bio_page.id"))
    created = db.Column(db.DateTime, nullable=False, default=db.func.now())


def save_bio_page_clicks(url_id, payload):
    # Get today's date components
    today = datetime.datetime.today()
    current_year = today.year
    current_month = today.month
    current_day = today.day

    # Query to find today's clicks for the given url_id
    clicks = BioPageClicks.query.filter(
        BioPageClicks.bio_page_id == url_id,
        extract("year", BioPageClicks.created) == current_year,
        extract("month", BioPageClicks.created) == current_month,
        extract("day", BioPageClicks.created) == current_day,
    ).first()

    if not clicks:
        print("save new click record")
        new_record = BioPageClicks(count=1, bio_page_id=url_id)
        db.session.add(new_record)
    else:
        print("update click record")
        clicks.count += 1

    db.session.commit()
    save_bio_page_click_location(
        payload["ip_address"],
        payload["country"],
        payload["city"],
        payload["device"],
        payload["browser_name"],
        url_id,
    )
    return True


# get bio page id
def get_bio_page_id(bio_name):
    bio_page = CreateBioPage.query.filter(
        func.lower(CreateBioPage.bio_name) == bio_name.lower()
    ).first()
    return bio_page.id


# update bio_page clicks
def update_bio_page_clicks(url_id):
    bio_page = CreateBioPage.query.get(url_id)
    bio_page.clicks += 1
    db.session.commit()
    return True


def save_bio_page_click_location(ip_address, country, city, device, browser, url_id):
    new_record = BioPageClickLocation(
        ip_address=ip_address,
        country=country,
        city=city,
        device=device,
        browser=browser,
        bio_page_id=url_id,
    )
    db.session.add(new_record)
    db.session.commit()

    return True

models/posts.py
from extensions import db
from sqlalchemy.orm import relationship
import datetime
from sqlalchemy import extract, func
from func import hex_id


class Categories(db.Model):
    __tablename__ = "categories"
    id = db.Column(db.String(50), primary_key=True, default=hex_id)
    name = db.Column(db.String(250), nullable=False)
    posts = relationship("Posts", backref="category")


class Posts(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.String(50), primary_key=True, default=hex_id)
    post_title = db.Column(db.String(250), nullable=False)
    post_content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=db.func.now())
    category_id = db.Column(db.String(50), db.ForeignKey("categories.id"))


def save_create_post(title, content, category_id):
    post = Posts(
        post_title=title,
        post_content=content,
        category_id=category_id
    )

    db.session.add(post)
    db.session.commit()

    return True


def get_posts(page, per_page, category_id=None):
    query = Posts.query.order_by(Posts.created_at.desc())

    if category_id:
        query = query.filter_by(category_id=category_id)

    # Apply pagination to the query
    paginated_posts = query.paginate(page=page, per_page=per_page, error_out=False)

    return paginated_posts


def get_one_post(post_id):
    return Posts.query.filter_by(id=post_id).first()


def get_categories():
    categories = Categories.query.all()
    return categories


# categ = ["QR code", "Link-in-bio", "URL shorter"]
#
# def create_categories():
#     for i in categ:
#         print(i)
#         category = Categories(name=i)
#         db.session.add(category)
#         db.session.commit()
#
#     return True

models/profile.py
from flask_login import UserMixin
from extensions import db
from sqlalchemy.orm import relationship
from func import hex_id


class CreateProfile(UserMixin, db.Model):
    __tablename__ = "users_links"
    id = db.Column(db.String(50), primary_key=True, default=hex_id)
    author_id = db.Column(db.String(50), db.ForeignKey("users.id"))
    description = db.Column(db.Text, default="")
    linkname = db.Column(db.String(250), nullable=False)
    link = db.Column(db.String(250), default="")
    link_name = db.Column(db.String(250), default="")
    clicks = db.Column(db.Integer, default=0)

views/user_view.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from forms import *
from models import *
from extensions import db
from flask_login import login_user, login_required, current_user
from models.bio_link_entries import CreateBioLinkEntries
from utils import (
    get_platform,
    generate_and_save_qr,
    update_qr_code,
    customize_qr_code_logo,
    customize,
    get_urls_by_date,
    get_qr_codes_by_date,
    get_bio_page_by_date,
    get_info,
    get_browser_info,
    get_computer_name,
)
from models.create_bio_page import CreateBioPage
from models.qr_code import QrCode, create_qr_want
from models.user import update_otp
from datetime import datetime
import matplotlib.pyplot as plt
import io
import base64
from werkzeug.security import generate_password_hash, check_password_hash
import qrcode
from PIL import Image
from sqlalchemy import func, extract
import traceback


user_blp = Blueprint("user_blp", __name__)


@user_blp.route("/", methods=["GET", "POST"])
def home():
    # form = GenerateBrandName()
    # posts = CreateProfile.query.all()
    if current_user.is_authenticated:
        return redirect(url_for("user_blp.dashboard"))
    if request.method == "POST" and "bt1" in request.form:
        original_url = request.form.get("url")
        if not original_url:
            flash("Input Required", "danger")
            return redirect(url_for("user_blp.home"))
        if not original_url.startswith("http://") and not original_url.startswith(
            "https://"
        ):
            original_url = "http://" + original_url
        check_if_exist = Urlshort.query.filter_by(url=original_url).first()
        if check_if_exist:
            print("url already exist")
            return render_template(
                "index.html",
                shortened_url=f"{request.host_url}{check_if_exist.short_url}",
                original_url=original_url,
                show=1,
                created=check_if_exist.created.strftime("%d, %b %Y %H:%M:%S"),
            )
        short_url = generate_short_url()

        url = Urlshort(
            url=original_url,
            short_url=short_url,
        )
        url.save()
        # flash('URL has been shortened successfully!', 'success')
        return render_template(
            "index.html",
            shortened_url=f"{request.host_url}{short_url}",
            original_url=original_url,
            show=1,
            created=url.created.strftime("%d, %b %Y %H:%M:%S"),
        )
    elif request.method == "POST" and "bt2" in request.form:
        brand_name = request.form.get("brandname").lower()
        if not brand_name:
            flash("Input Required", "danger")
            return redirect(url_for("user_blp.home"))
        user_ = User.query.filter_by(brand_name=brand_name).first()
        if user_:
            # User with that brand already exists
            flash("Brand Name already exists!", "danger")
            return redirect(url_for("user_blp.home"))
        return redirect(url_for("auth_blp.register", brandie=brand_name))
    return render_template("index.html")


@user_blp.route("/user/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    try:
        user_id = current_user.id
        brand_url = f"{request.host_url}{current_user.brand_name}"
        posts = CreateProfile.query.filter_by(author_id=user_id).all()

        url_short = Urlshort.query.filter_by(author_id=user_id).all()

        qr_codes_ = QrCode.query.filter_by(author_id=user_id).all()

        host_url = request.host_url
        brandie = current_user.brand_name

        return render_template(
            "dashboard.html",
            brand_url=brand_url,
            brandie=brandie,
            host_url=host_url,
            url_short=url_short,
            qr_codes_=qr_codes_,
            dashboard=True,
        )
    except Exception as e:
        print(e, "error@dashboard")
        db.session.rollback()
        return redirect(url_for("user_blp.home"))


@user_blp.route("/join", methods=["GET", "POST"])
def join():
    # Every render_template has a logged_in variable set.
    form = GenerateBrandName()
    if request.method == "POST":
        brand_name = request.form.get("brandname")
        user_ = User.query.filter_by(brand_name=brand_name).first()
        if user_:
            # User already exists
            flash("Brand Name already exists!")
            return redirect(url_for("home"))

        new_user = User(brand_name=brand_name)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for("auth_blp.register"))
    return render_template("join.html", form=form, current_user=current_user)


@user_blp.route("/create-bio-page", methods=["GET", "POST"])
@login_required
def create_Bio_Page():
    # Create Bio Pages.
    form = GenerateBrandName()
    if request.method == "POST":
        bio_name = request.form.get("brandname")
        if not bio_name:
            flash("Input Required", "danger")
            return redirect(url_for("user_blp.create_Bio_Page"))
        if " " in bio_name:
            flash("Bio Name cannot contain spaces", "danger")
            return redirect(url_for("user_blp.create_Bio_Page"))
        user_ = CreateBioPage.query.filter_by(bio_name=bio_name).first()
        if user_:
            # User already exists
            flash("Name already exists! Choose a unique name", "danger")
            return render_template(
                "createBioPage.html", form=form, current_user=current_user
            )

        new_user = CreateBioPage(bio_name=bio_name, author_id=current_user.id)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for("user_blp.bio_link_pages", bio_id=new_user.id))
    return render_template("createBioPage.html", form=form, current_user=current_user)


# Edit Bio Name
@user_blp.route("/biolinkpages/<path:sub_path>/edit_name", methods=["GET", "POST"])
@login_required
def edit_bio(sub_path):
    # form = GenerateBrandName()
    b = CreateBioPage.query.filter_by(
        bio_name=sub_path, author_id=current_user.id
    ).first()
    bio_links = CreateBioLinkEntries.query.filter_by(
        author_id=current_user.id, bio_page_id=b.id
    ).all()
    # brandname = request.form.get("brandname")
    # if not brandname:
    #     flash("Input Required", "danger")
    #     return redirect(url_for("user_blp.dashboard"))
    # user_ = User.query.filter_by(brand_name=brandname.lower()).first()
    # if user_:
    #     # User with that brand already exists
    #     flash("Brand Name already exists!", "danger")
    #     return redirect(url_for("user_blp.dashboard"))
    # current_user.brand_name = brandname.lower()
    # db.session.commit()
    # flash("Brand Name updated successfully!", "success")
    return redirect(url_for("user_blp.bio_link_pages_details", links_added=bio_links))


# list all bio pages
@user_blp.route("/display_all/biolinkpages", methods=["GET", "POST"])
@login_required
def bio_link_pages():
    user_name = current_user.username
    bio_pages = CreateBioPage.query.filter_by(author_id=current_user.id).all()
    bio_links = CreateBioLinkEntries.query.filter_by(author_id=current_user.id).all()
    host_url = request.host_url

    display = True if bio_pages else False
    refresh = False

    if request.method == "POST":
        date_filter = request.form.get("date")
        print(date_filter, "date")

        bio_pages = get_bio_page_by_date(date_filter)
        display = True
        refresh = True
    print(bio_pages, "Pages bio")
    # update the bio name
    return render_template(
        "biolinkpages.html",
        host_url=host_url,
        bio_pages=bio_pages,
        links_added=bio_links,
        display=display,
        refresh=refresh,
        bio=True,
    )


@user_blp.route("/BioLinkPages/<bio_id>", methods=["POST"])
@login_required
def update_bio_link_pages(bio_id):
    brandname = request.form.get("brandname")
    if not brandname:
        flash("Input Required", "danger")
        return redirect(url_for("user_blp.bio_link_pages"))
    brand_n = CreateBioPage.query.filter_by(bio_name=brandname.lower()).first()
    brand_name = CreateBioPage.query.filter_by(
        id=bio_id, author_id=current_user.id
    ).first()
    if brand_n and brand_name.bio_name.lower() != brandname.lower():
        # User with that brand already exists
        flash("Bio Name already exists!", "danger")
        return redirect(url_for("user_blp.bio_link_pages"))
    brand_name.bio_name = brandname.lower()
    db.session.commit()
    flash("Bio Name updated successfully!", "success")
    return redirect(url_for("user_blp.bio_link_pages"))


@user_blp.route("/bio/update/<bio_id>", methods=["POST"])
@login_required
def update_details(bio_id):
    brandname = request.form.get("brandname")
    print(bio_id, "idddd")
    if not brandname:
        flash("Input Required", "danger")
        return redirect(url_for("user_blp.bio_link_pages"))
    brand_n = CreateBioPage.query.filter_by(bio_name=brandname.lower()).first()
    brand_name = CreateBioPage.query.filter_by(
        id=bio_id, author_id=current_user.id
    ).first()
    if brand_n and brand_name.bio_name.lower() != brandname.lower():
        # User with that brand already exists
        flash("Bio Name already exists!", "danger")
        return redirect(url_for("user_blp.bio_link_pages"))
    brand_name.bio_name = brandname.lower()
    db.session.commit()
    flash("Bio Name updated successfully!", "success")
    return redirect(url_for("user_blp.bio_link_pages_details", bio_id=bio_id))


@user_blp.route("/biolinkpages/<bio_id>/build", methods=["GET", "POST"])
@login_required
def bio_link_pages_details(bio_id):
    form = CreatePostForm()
    # bio_pages = CreateBioPage.query.filter_by(author_id=current_user.id).all()
    host_url = request.host_url
    bio_links = CreateBioLinkEntries.query.filter_by(

templates/bio_link_page_appearance.html
{% extends 'base2.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dashboard.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/biophone.css') }}">


{% endblock head %}
{% block content %}

<main style="margin-top: 78px">
  <div class="container pt-4">
      <ul class="breadcrumb">
      <li><a href="#">Bio pages</a></li>
      <li>Appearance</li>
       </ul>

    <!--Start of Bio link Nav Bar-->
   {% include "biolink_navbar.html" %}
       <!--End of Bio link Nav Bar-->

<br>



<div class="container mt-3">
    <h3 class="mb-2"><b>DESIGN BIO PAGE APPEARANCE</b></h3>

    <div class="row">
     <div class=""  >
         <div class="float-start  w-50" >

         <div class="card border border-light bg-light ">

             <h4 class="mx-5 mt-4"><b>Profile</b></h4>
             <h6 class="mx-5 mt-2"><b>Image</b></h6>
           <br>

             <div class="row">

             <div class="d-flex justify-content-left mb-4 mx-5 float-start">
            <img src="{{ url_for('static', filename='Image-place-holder.png') }}"
            class="rounded-circle "  style="width: 100px; height: 100px; object-fit: cover;" alt="example placeholder" />

                 <div class=" text-center mt-4 ms-4">
                   <button class="rounded-3">Add Image</button>
               </div>

            </div>

               <h5 class="mx-5 mt-4"><b>About</b></h5>
               <p class="mx-5 mt-2"><b> About</b>(Optional)</p>
               <p class="mx-5 mt-0"> <input type="text" id="fname" name="fname" size="40" value="Welcome!"></p>

               <p class="mx-5 mt-2"><b> Description</b>(Optional)</p>
               <p class="mx-5 mt-0"> <input type="text" id="des" name="desc" size="40" value=""></p>
                 <br>
            </div>
         </div> <br>

             <div class="float-start  w-100" >
            <div class="card border border-light bg-light ">
             <h5 class="mx-5 mt-4"><b>Style & layout</b></h5>
             <h6 class="mx-5 mt-2"><b>Bio Layout</b></h6>

             <div class="d-flex justify-content-left mb-4 mx-5 float-start ">
            <img src="{{ url_for('static', filename='Layout-1.png') }}" style="width: 100px; height: 200px; object-fit: cover;" alt="example placeholder" />

            <img src="{{ url_for('static', filename='Layout-2.png') }}" class="ms-5" style="width: 100px; height: 200px; object-fit: cover;" alt="example placeholder" />

            <img src="{{ url_for('static', filename='Layout-3.png') }}" class="ms-5" style="width: 100px; height: 200px; object-fit: cover;" alt="example placeholder" />

             </div>
             </div>
             </div>

              <h5 class="mx-5 mt-4">.</h5>
             <div class="float-start  w-200" >
            <div class="card border border-light bg-light ">
              <h5 class="mx-5 mt-4"><b>Block</b></h5>
                <h6 class="mx-5 mt-2"><b>Shape</b></h6>

                <div>
                    <img src="{{ url_for('static', filename='Rectangle-11.png') }}" class="ms-5 float-start" style="width: 200px; height: 50px; object-fit: cover;" alt="example placeholder" />
                    <img src="{{ url_for('static', filename='Rectangle-12.png') }}" class="ms-3 me-4 float-end" style="width: 200px; height: 50px; object-fit: cover;" alt="example placeholder" />
                </div>

                <div class="mt-3">
                    <img src="{{ url_for('static', filename='Rectangle-16.png') }}" class="ms-5 float-start" style="width: 200px; height: 50px; object-fit: cover;" alt="example placeholder" />
                    <img src="{{ url_for('static', filename='Rectangle-14.png') }}" class="ms-3 me-4 float-end" style="width: 200px; height: 50px; object-fit: cover;" alt="example placeholder" />
                </div>

                <div class="mt-3 mb-5">
                    <img src="{{ url_for('static', filename='Rectangle-13.png') }}" class="ms-5 float-start" style="width: 200px; height: 50px; object-fit: cover;" alt="example placeholder" />
                    <img src="{{ url_for('static', filename='Rectangle-15.png') }}" class="ms-3 me-4 float-end" style="width: 200px; height: 50px; object-fit: cover;" alt="example placeholder" />
                </div>
<!--                  <h6 class="mx-5 mt-2"><b>Shadow</b></h6>-->
<!--                 <div class="mt-3 mb-5">-->
<!--                    <img src="{{ url_for('static', filename='shadow-1.png') }}" class="ms-2 float-start" style="width: 100px; height: 50px; object-fit: cover;" alt="example placeholder" />-->
<!--                    <img src="{{ url_for('static', filename='shadow-2.png') }}" class="ms-2  float-center" style="width: 150px; height: 50px; object-fit: cover;" alt="example placeholder" />-->
<!--                     <img src="{{ url_for('static', filename='shadow-3.png') }}" class="ms-2 float-end" style="width: 200px; height: 50px; object-fit: cover;" alt="example placeholder" />-->
<!--                </div>-->

                </div>
                 </div>






      </div>






         <!-- Bio details phone-->
       <div class="float-end">
           <p class="text-center rounded-pill "><button class="rounded-3 bg-warning ">Live Preview </button></p>
      <div class="smartphone ">
     <div class="content mx-5" >
      <div class="phone_container mt-5 mx-5" >

          <div class="d-flex justify-content-center mb-4 mx-5 ">
            <img src="{{ url_for('static', filename='Image-placeholder-2.png') }}"
        class="rounded-circle "  style="width: 100px; height: 100px; object-fit: cover;" alt="example placeholder" />
            </div>

          <p class="text-center"><b>Welcome!</b></p>

      {% for post in links_added|reverse%}
          <div class='border border-primary rounded-pill p-3 mt-2 text-center'>
              <img class="rounded-circle" height="25" width="25" src='http://www.google.com/s2/favicons?domain={{post.link_url}}' />
        {{ post.link_name.upper() }} <br>
              </div>
      {% endfor %}

          </div>
      </div>
    </div>
  </div>
</div>

</div>





</div>

  </div>
</main>
{% endblock content %}

templates/bio_link_routes.html
{% extends 'base3.html' %}
{% block title %}- {{brandie}} Link-in-bio Page{% endblock title %}
{% block content %}

<style>
    .containerr {
        max-width: 600px;
        max-height: 10px;
        margin: 0 auto;
        padding: 40px 20px;
        text-align: center;
        border-radius: 8px;
        font-family: proxima nova;


    }

    h1 {
        font-size: 36px;
        color: #333;
        margin-top: 0;
    }
</style>
           <div class="text-end mx-5 ml-5 mb-5 rounded-circle "><button class="rounded-circle border border-light mx-5 px-2"><i class="bi bi-share-fill" ></i></button></div>
<div class="containerr mt-5">


    <button class="rounded-pill"><i class="text-center fa fa-user h1 text-primary stylethis2 mx-3 mt-3 mb-3"></i></button>
    <br><br>
    <div class='h3 mb-4 mt-3'><strong>Welcome!</strong></div>

    {%if all_posts%}
    {% for post in all_posts  %}
    <div class='p-3 mt-2 rounded-pill border-bottom ' style="color: rgb(35, 35, 35); background-color: rgb(199, 204, 208); border-radius: 2.3rem;">
        <img class="me-5 rounded-circle" height="25" width="25" src='http://www.google.com/s2/favicons?domain={{post.link_url}}' />
        <a class='h3 mb-4 mt-3 fw-bold text-decoration-none' href='{{post.link_url}}' target='_blank'>{{ post.link_name.upper() }}</a>
        <div style='display: flex; justify-content: space-evenly;'>
            {%if post.link_name=="Twitter" %}
            <a href='{{post.link}}' target='_blank'>
                <i class="fa-brands fa-twitter h1 text-info"></i>
            </a>
            {%endif%}
            {%if post.link_name=="Amazon" %}
            <a href='{{post.link}}' target='_blank'>
                <i class="fa-brands fa-amazon h1 text-warning"></i>
            </a>
            {%endif%}
            {%if post.link_name=="Facebook" %}
            <a href='{{post.link}}' target='_blank'>
                <i class="fa-brands fa-facebook h1"></i>
            </a>
            {%endif%}
            {%if post.link_name=="Youtube" %}
            <a href='{{post.link}}' target='_blank'>
                <i class="fa-brands fa-youtube h1 text-danger"></i>
            </a>
            {%endif%}
        </div>
    </div>
    {% endfor %}
    {%else%}
    <h1>
        THIS IS {{brandie}}'S SPECIAL PAGE
    </h1>
    {%endif%}
</div>
{% endblock content %}

templates/biolink_navbar.html
<!--start of bio link nav bar -->

<div class="dashdiv">
     <div class="d-flex flex-row">
        <div class="p-2">
   <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 flex-fill text-start">

       {% for post in bios %}
       <li class="nav-item mx-3">
        <p class="mt-1"><i class="fa fa-link" aria-hidden="true"></i>
        <a class="text-decoration-none text-dark fw-bold " href="{{url_for('user_blp.bio_link_routes', brand_name=post.bio_name)}}" >{{ host_url }}bio/{{post.bio_name}}</a></p>
       </li>

       <li class="nav-item mt-1"><span class="text-primary text-center "><b><i class="fas fa-copy"></i> Copy</b></span></li>

       <li>
       <div class="dropdown mx-3">
       <button class="btn btn-secondary dropdown-toggle mt-0" type="button" id="dropdownMenu3" data-bs-toggle="dropdown" aria-expanded="false">
       <i class="bi bi-pencil-square"></i> Edit URL </i>
       </button>

           <!-- Edit Bio page dropdown -->
      <div class="dropdown-menu p-5" style="width: 20rem;">
      <h3>Edit Bio Name</h3>
      <form action="{{url_for('user_blp.update_details', bio_id=post.id)}}" method="post" class="form-group">
        <label for="link_name">Link Name</label>
        <input type="text" class="form-control" name="brandname" value={{post.bio_name}}> <br>
        <button type="submit" class="btn btn-secondary">Update</button>
      </form>
      </div>
      </div>
      </li>

      <li><a href="{{url_for('user_blp.bio_link_routes', brand_name=post.bio_name)}}" target="blank">
          <button class="btn-light text-center p-1 bg-light shadow-none mx-3 text-dark text-decoration-none rounded-3 border border-dark">
           <i class="fa fa-external-link mx-1" aria-hidden="true"></i> View </button></a>
      </li>

      <li>
      <button class="popup btn-light text-center p-1 bg-light shadow-none  text-dark text-decoration-none rounded-3 border border-dark" href="#" onclick="myFunction()"><i class="fas fa-share"></i> Share</i>
       <span class="popuptext mt-5" id="myPopup">



       </span>

       </button>
       </li>



       <li class="text-end ms-5"><p class="btn-success text-end p-1 ms-5 bg-success shadow-none text-light text-decoration-none rounded-1 border border-success" >
            Publish Changes
       </p>
       </li>


       {% endfor %}
    </ul>
    </div>
    </div>
</div>

      <div class="container bg-secondary">
    <div class="d-flex justify-content-start py-3 container align-item-center">
        <div>
            {% for post in bios %}
        <a href="{{url_for('user_blp.bio_link_pages_details', bio_id=post.id)}}" class="py-1 px-2 text-decoration-none {% if bio_details %} text-primary bg-white h5 {% else %}text-white {% endif %}" style="background: rgb(93, 87, 80) !important;">Create</a>
        <a href="{{url_for('user_blp.bio_link_page_appearance', bio_id=post.id)}}" class="py-1 px-2 text-decoration-none {% if bio_appearance %} text-primary bg-white h5 {% else %}text-white {% endif %}" style="margin-right: .6rem; background: rgb(93, 87, 80) !important;">Appearance</a>
        <a href="{{url_for('user_blp.bio_link_page_track_analytics', bio_id=post.id)}}" class="py-1 px-2 text-decoration-none {% if bio_analytics %} text-primary bg-white h5 {% else %}text-white {% endif %}" style="background: rgb(93, 87, 80) !important;">Analytics</a>
            {% endfor %}
    </div>
    </div>
</div>




<!--End of bio link nav bar -->

templates/one_post.html
{% extends 'base.html' %}
{% block content %}

<style>

  .post {
    /* background-color: #fff; */
    border: 1px solid #dee2e6;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 20px;
    position: relative; /* Needed for absolute positioning of comment icon */
    /* From https://css.glass */
    background: rgba(0, 0, 0, 0.668);
    border-radius: 16px;
    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
    backdrop-filter: blur(4px);
    -webkit-backdrop-filter: blur(4px);
    border: 1px solid rgba(11, 11, 11, 0.28);
    color: white;
  }

  .post img {
    width: 600px;
    height: 600px;
    border-radius: 4px;
    margin-bottom: 10px;
    margin: auto;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .category_name {
    position: absolute;
    top: 15px;
    right: 15px;
    z-index: 999;
  }
</style>

  <section class="container mt-5">
      {% if post %}
      <!-- First Row -->
    
        <!-- Post 1 -->
        <div class="post">
          <h5 class="mb-3 text-center">{{post.post_title}}</h5>
          <hr>
          <p>{{ post.post_content|safe }}</p>
          <span class="category_name badge bg-warning text-dark">{{post.category.name}}</span>
</div>
        </div>

    {% endif %}

  </section>

{% endblock content %}